language: c
compiler: gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - build-essential

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

script:
  - cd build
  - cmake ..
  - make
  - make test