language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install build-essential
  - sudo apt-cache search qt

script:
  - mkdir build
  - cd build
  - cmake ../src
  - make