language: c
os:
  - linux
  - osx

#addons:
#  apt:
#    packages:
#    - build-essential
#    - libxml2-dev

script:
  - cd build
  - cmake .. && cmake --build . && ctest

before_deploy:
  - cd ..
  - export EXP_ZIP_FILE=${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_OS_NAME}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  - echo zip file is ${EXP_ZIP_FILE} from ${TRAVIS_BUILD_DIR}
  - tar -zcf ${EXP_ZIP_FILE} ${TRAVIS_BUILD_DIR}

deploy:
  provider: releases
  api_key:
    secure: vi4WZCLv25nsJcZgGpYeWex82E6CRyjHTzTpAw11ueobeRMuWr/CGz+ZASk6Gvb3DPYVqN42C8+AsFtxTNl73dJWUcy1U6VWnqDokFr8VEmoGwfIN9Xo76Ikpfi3ixOdE/6X2xhFE5QFVyv+2caznK1tpN30YWSifVm9KinFqHYopyHp3bEZarqiwluvh2g8iNnr0t9Try/cSW2oCeII33m5KWdjcLodd7R2hX9vaGvmrbOLQ/OZInmIsqibciCFGagz20c6iXXj8QS9hz3yMda+7eHwZCF52pGNOPCdZwyrT3hITSYLp3wgPNPzatOEOQGd59AYfXurN5wYGjUI8vRqjLFgsiE46zR/45ZE/wuefgKlHpRunoQs4DQFNGJHKYDtYOQ/Ua7oJSO1dD7dYnc0VNEX4ve5hDCPd9HfxYcnJn99V4H3xFrG6g5QeWXxfgBgAKPyH8vCIMxhSTqz5G7PBzF2Tuvf3EnUxPsgEKOEwFM/wWucpjMVMLdpOsfybtMwHbKPEANnOcxgtMrXBIt0j9HAvoAC6k9ttDyLeExgWutnGLOGImNKErejCXlyXqQDvMtUinyQydR+MOTTEBuRizGD94E8CjDjopeA6hzSF12FicZVqZZY1A+8kUlopk7X5cCmm4LGR4H565jCYVvZsmGKPNZY55HPE1wt9nE=
  file: '${EXP_ZIP_FILE}'
  skip_cleanup: true
  on:
    tags: true
