image: Visual Studio 2017

#environment:
#  matrix:
#  - QT: C:\Qt\5.7\msvc2015_64
#    PLATFORM: amd64
#    COMPILER: msvc
#    VSVER: 14

clone_depth: 1

build_script:
  - cd build
  - cmake ..
  - make