image: Visual Studio 2017

#environment:
#  matrix:
#  - QT: C:\Qt\5.7\msvc2015_64
#    PLATFORM: amd64
#    COMPILER: msvc
#    VSVER: 14

clone_depth: 1

build_script:
#  - vcpkg search sqlite
#  - vcpkg search libxml2
#  - vcpkg search yaml
#  - vcpkg install libxml2
  - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P libyaml-devel -P libxml2-devel -P cmake
#  - cd build
#  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
#  - make
  - set PATH=C:\cygwin64\bin;%PATH%
  - echo %PATH%
  - cd build && cmake .. && cmake --build . 
#  - C:\cygwin64\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; cd build; /cygdrive/c/cygwin64/bin/cmake .. ; /cygdrive/c/cygwin64/bin/cmake --build ." 