image: Visual Studio 2015

init:
  - dir C:\Qt\5.10.0
  - dir C:\Qt\5.10.0\msvc2015_64
  - dir C:\Qt\5.10.0\msvc2015_64\bin
  - dir C:\Qt\5.10.0\msvc2015_64\lib
  - set QTDIR=C:/Qt/5.10.0/msvc2015_64
  - set PATH=%QTDIR%\bin;%PATH%
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

install:
  - vcpkg install libxml2:x64-windows
  - git clone https://github.com/yaml/libyaml
  - cd libyaml && cmake -G "Visual Studio 14 2015 Win64"  -DBUILD_SHARED_LIBS=a . && cmake --build . --target install && cd ..
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_MODULE_PATH="C:/Program Files/yaml/cmake" -DCMAKE_PREFIX_PATH="c:/tools/vcpkg/installed/x64-windows;C:/Program Files/yaml" . 
  - cmake --build . --target install
  - 7z a libsndwch.zip "C:/Program Files/sample/"

artifacts:
  - path: libsndwch.zip
    name: libsndwch
