image: Visual Studio 2017

#environment:
#  matrix:
#  - QT: C:\Qt\5.7\msvc2015_64
#    PLATFORM: amd64
#    COMPILER: msvc
#    VSVER: 14

clone_depth: 1

build_script:
  - vcpkg search sqlite
  - vcpkg search libxml2
  - vcpkg search yaml
  - vcpkg install libxml2
  - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P libyaml-devel
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - make