image: Visual Studio 2017

#environment:
#  matrix:
#  - QT: C:\Qt\5.7\msvc2015_64
#    PLATFORM: amd64
#    COMPILER: msvc
#    VSVER: 14

clone_depth: 1

build_script:
  - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P libyaml-devel -P libxml2-devel -P libiconv-devel -P cmake
  - set PATH=C:\cygwin64\bin;%PATH%
  - echo %PATH%
#  - cd build && cmake -G "Visual Studio 15 2017 Win64" .. && cmake --build .
  - cd build && cmake .. && cmake --build . 
